# Setup
title:              Justgizzmo.com

# Exclude these files from the production _site
exclude:
    - CNAME
    - README.md

# for github pages
# gems:
# - jekyll-github-metadata
# - jekyll-mentions
# - jekyll-redirect-from
# - jekyll-sitemap
# - jemoji